modLoader="javafml"
loaderVersion="[36,)"
license="Prive - Aller & Retour. Base sur le mod LOTR de Mevans, non redistribuable."

[[mods]]
modId="lotr"
version="${file.jarVersion}"
displayName="LOTR Aller & Retour"
authors="Ando"
description='''
Portage prive du mod Lord of the Rings (Legacy 1.7.10) vers Forge 1.16.5
pour le serveur roleplay Aller & Retour.
'''

[[dependencies.lotr]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.lotr]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
